import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Pacifico,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "./globals.css";
import { Footer, Header, NavigationBar, TopBar } from "@/components";
import { ServiceHighlights } from "@/components/home";
import Providers from "@/components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pacifico = Pacifico({
  weight: "400",
  variable: "--font-pacifico",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} ${plusJakartaSans.variable} antialiased`}
      >
        <Providers>
          <TopBar />
          <Header />
          <NavigationBar />

          <main className="min-h-screen">{children}</main>
          <ServiceHighlights />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
